name: flutteruikit
description: A new Flutter project.


publish_to: 'none'


version: 6.1.0
versionCode: 4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: ^2.0.0

  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1

  syncfusion_flutter_core: ^19.4.38
  syncfusion_flutter_calendar: ^19.4.38
  syncfusion_flutter_datepicker: ^19.4.38
  syncfusion_flutter_sliders: ^19.4.38
  syncfusion_flutter_charts: ^19.4.38
  syncfusion_flutter_gauges: ^19.4.38

  google_maps_flutter: ^2.0.3
  shimmer: ^2.0.0
  url_launcher: ^6.0.3
  intl: ^0.17.0

  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0


flutter:

  uses-material-design: true


  assets:

    - assets/map/


    - assets/images/profile/


    - assets/images/all_apps/shopping_app/
    - assets/images/all_apps/shopping_app/product/
    - assets/images/all_apps/shopping_app/offer/
    - assets/images/all_apps/shopping_app/camera/
    - assets/images/all_apps/shopping_app/vector/


    - assets/brandImg/

    - assets/images/all_apps/hotel/

    - assets/images/places/

    - assets/images/all_apps/music/

    - assets/images/all_apps/foodImg/

    - assets/images/all_apps/estate_app/

    - assets/images/all_apps/course/

    - assets/images/all_apps/chat/

    - assets/images/all_apps/social/

    - assets/images/all/

    - assets/images/all_apps/event/


    - assets/images/all_apps/grocery_app/

    - assets/images/all_apps/homemade_app/
    - assets/images/all_apps/homemade_app/products/
    - assets/images/all_apps/homemade_app/category/
    - assets/images/all_apps/homemade_app/shop/
    - lib/all_apps/homemade_app/data/

    - assets/images/all_apps/dating_app/

    - assets/images/all_apps/movies_app/
    - lib/all_apps/movies_app/data/

    - assets/images/all_apps/cookify_app/
    - assets/images/all_apps/grocery_app/
    - assets/images/all_apps/medicare_app/

    - assets/images/all_apps/learning/images/
    - assets/images/all_apps/learning/icons/

    - lib/all_apps/dating_app/data/

    - assets/illustration/foodImg/
    - assets/illustration/shopping_app/
    - assets/illustration/hotel/
    - assets/illustration/music/

    - assets/images/month_background/

    - assets/lang/

    - assets/icons/

    - assets/otherImg/